CREATE TABLE IF NOT EXISTS cdn_streaming_stats (
  id int(10) unsigned NOT NULL AUTO_INCREMENT,
  vsqsessionid text,
  vsqdomain text,
  vsqrecordingfeed text,
  wowzasessionid text,
  starttime datetime NOT NULL,
  endtime datetime DEFAULT NULL,
  vsquserid int(10) DEFAULT NULL,
  httpsessionid text,
  wowzaappid text,
  sessiontype enum('unknown','live','livedvr','vod') NOT NULL,
  wowzalocalstreamname text,
  wowzaremotestreamname text,
  wowzaclientid text,
  rtspsessionid text,
  streamingtype enum('unknown','cupertino','dvrchunks','mpegdash','sanjose','smoothstreaming','webmstreaming','rtsp','rtmp') NOT NULL,
  serverip text,
  clientip text,
  encoder int(10) NOT NULL DEFAULT '0',
  url text,
  referrer text,
  clientplayer text,
  PRIMARY KEY (id),
  KEY http_idx (httpsessionid(16),serverip(16)),
  KEY rtmp_idx (wowzaclientid(16),serverip(16)),
  KEY rtsp_idx (rtspsessionid(16),serverip(16))
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
