#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          hv_kvp_daemon
# Required-Start:    $null
# Should-Start:      $syslog $remote_fs $time
# Required-Stop:     $null
# Should-Stop:       $syslog $remote_fs $time
# Default-Start:     2 3 5
# Default-Stop:      0 1 6
# Short-Description: hv_kvp_daemon provides info to the host
# Description:       Start hv_kvp_daemon to allow the host to query this guest
### END INIT INFO

#. /etc/rc.d/init.d/functions

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/hv_kvp_daemon
DAEMON_ARGS=
NAME=hv_kvp_daemon
DESC=hv_kvp_daemon
RUNDIR=/var/run/hv_kvp_daemon
PIDFILE=$RUNDIR/hv_kvp_daemon.pid

set -u
${DEBIAN_SCRIPT_DEBUG:+ set -v -x}

test -x $DAEMON || exit 0

if [ -r /etc/default/$NAME ]
then
        . /etc/default/$NAME
fi

. /lib/lsb/init-functions

set -e

case "$1" in
  start)
	if ! status_of_proc -p ${PIDFILE} ${DAEMON} ${NAME} >&/dev/null; then

		echo -n "Starting Hyper-V KVP daemon "
		mkdir -p $RUNDIR
        touch $PIDFILE

		if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --chuid root:root --exec $DAEMON -- $DAEMON_ARGS
        then
        	echo "$NAME."
        else
        	echo "failed"
        fi
	else
		echo -n "Hyper-V KVP daemon is already started"
	fi
    ;;
  stop)
	echo -n "Shutting down Hyper-V KVP daemon "
	killall -15 $DAEMON
    rm -f $PIDFILE
    sleep 1
	echo
	;;
  status)
	status_of_proc -p ${PIDFILE} ${DAEMON} ${NAME}
    ;;
  *)
  	echo "Usage: /etc/init.d/$NAME {start|stop|status}" >&2
    exit 1
    ;;
esac

exit 0
